#!/usr/bin/env bash
#install haproxy as load balancer and configure it to direct traffic

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen load_balancer 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption forwardfor\n\toption httpclose\n\tserver 3048-web-01 34.204.176.35:80 check\n\tserver 3048-web-02 3.238.177.139:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
